# Otantamenetelmät (Demo 1)

## Exercise 1

Estimating the number of mooses in Taivakoski area by light aircraft. The evaluated area covers about 10% of total area. Observed numbers for each route are 6, 7, 0, 20, 0, 0, 23, 2, 0. Define the mean value and its standard error. Estimate the total number in the area and its 95% confidence interval.

<blockquote>
This is a simple random sampling problem, and we simplify the sampling to be 9 out of the population of 90 routes ($n=9,\ N=90$)
$$\begin{aligned} 
 \text{mean number per route }\bar y &= \frac 1 n \sum\limits_{i=1}^n y_i = 6.44
\\ \text{SE}(\bar y)&= \sqrt{ \bigg( 1 - \frac n N \bigg) \frac{s^2} n }= \sqrt {0.1 s^2} = 2.84
\\ \text{area total mooses } \hat\tau &= N \bar y = 580
\\ \hat{\text{Var}}(\hat\tau)  &= N(N-n) \frac {s^2} n = 65227.5
\\ \text{confidence interval } & 580 \pm 1.96 \times 255.4 \text{ i.e. } (79.42,\ 1080.58)
\end{aligned}$$
</blockquote>

## Exercise 2

Check the finite popluation correction using a simple example $\{0,1,2\}$ with $N=3, \ n=2$ with and without replacement.

<blockquote>
Without replacement
$$\begin{aligned} 
\{0,1\} &\ s^2 = 0.5 &\ \ \sigma^2 = 0.25  \\
\{0,2\} &\ s^2 = 2 &\ \ \sigma^2 = 1.00\\
\{1,2\} &\ s^2 = 0.5 &\ \ \sigma^2 = 0.25
\end{aligned}$$

With replacement
$$\begin{aligned} 
\{0,0,0\} &\ s^2 = 0  &\ \ \sigma^2 = 0\\
\{0,0,1\} &\ s^2 = 0.33  &\ \ \sigma^2 = 0.22\\
\{0,0,2\} &\ s^2 = 1.33 &\ \ \sigma^2 = 0.89 \\
\{0,1,1\} &\ s^2 = 0.33  &\ \ \sigma^2 = 0.22\\
\{0,1,2\} &\ s^2 = 1  &\ \ \sigma^2 = 0.67 \\
\{1,1,1\} &\ s^2 = 0  &\ \ \sigma^2 = 0\\
\{1,1,2\} &\ s^2 = 0.33  &\ \ \sigma^2 = 0.22\\
\{1,2,2\} &\ s^2 = 0.33  &\ \ \sigma^2 = 0.22\\
\{2,2,2\} &\ s^2 = 0  &\ \ \sigma^2 = 0
\end{aligned}$$
</blockquote>

## Exercise 3

There are 100 small households in the new district. SRS checked 10 household size, which are  1, 3, 4, 6, 5, 4, 3, 2, 5, 2. Estimate the population (total number) and its variance, as well as mean household size and its variance.

<blockquote>
$$\begin{aligned} 
\ \hat\tau &= N \bar y = 350
\\ \hat{\text{Var}}(\hat \tau) & = N(N-n) \frac {s^2} n = 2250
\\ \hat\mu &= \bar y= 3.5
\\ \hat{\text{Var}}(\bar y)&=  \bigg( 1 - \frac n N \bigg) \frac{s^2} n = 0.09 s^2 = 0.225
\end{aligned}$$
</blockquote>

## Exercise 4

Consider population mean estimator. Suppose for all case the population variance are the same $S^2$. a) $N=500,\ n=50$; b) $N=4000,\ n=400$ and c) $N= 300 000 000,\ n = 3000$.

<blockquote>
$$\begin{aligned} 
\text{Var}(\bar y)= &\bigg( 1 - \frac n N \bigg) \frac{S^2} n = \bigg( \frac 1 n - \frac 1 N \bigg) S^2
\\ \text{a) } \text{Var}_a(\bar y)&= 0.018 S^2
\\ \text{b) } \text{Var}_b(\bar y)&= 0.00225 S^2
\\ \text{c) } \text{Var}_c(\bar y)&= 0.00033 S^2
\end{aligned}$$

While the estimator itself stay constant ($\hat \mu=\bar y$), its variance is smaller given large propotion of sampling ($n/N$). Furthemore, larger $n$ usually leads to smaller variance.
</blockquote>

## Exercise 5

There are 10000 shelves in the library, which are all 200cm tall. The manager want to estimate how many books needs fix. He plans to pick 50 books by the following strategy: first select a random number from 1-10000 for shelf, and then 1-200 to pick the position where the book stays. Repeat 50 times. Why it is not an SRS? What is this sampling? How to achieve SRS?

<blockquote>
Each shelf may have different number of books, and each books may have different size, therefore the probability for the book to be picked are not constant. This sampling is proportional per size (PPS) sampling.

SRS can be achieved by sampling from the book number.
</blockquote>